package com.afms.cahgame.util;

import android.content.SharedPreferences;

import com.afms.cahgame.data.Card;
import com.afms.cahgame.data.Colour;
import com.afms.cahgame.game.Deck;
import com.github.javafaker.Faker;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class Util {
    public static boolean godMode = false;
    public static String playerName;

    /**
     * Converts a dataDeck to a GameDeck by getting all the card data from the database.
     *
     * @param dataDeck The dataDeck.
     * @return The newly created GameDeck.
     */
    public static Deck convertDataDeckToPlayDeck(com.afms.cahgame.data.Deck dataDeck) {
        Deck gameDeck = new Deck();
        gameDeck.setName(dataDeck.getName());

        if (dataDeck.getCardIds() == null || dataDeck.getCardIds().size() == 0) {
            return gameDeck;
        }

        List<com.afms.cahgame.game.Card> blackCards = new ArrayList<>();
        List<com.afms.cahgame.game.Card> whiteCards = new ArrayList<>();

        for (int cardId : dataDeck.getCardIds()) {
            Card dataCard = getDataCardFromId(cardId);
            if (dataCard != null) {
                if (dataCard.getColour().equals(Colour.WHITE)) {
                    whiteCards.add(new com.afms.cahgame.game.Card(dataCard.getId(), dataCard.getColour(), dataCard.getText()));
                } else {
                    blackCards.add(new com.afms.cahgame.game.Card(dataCard.getId(), dataCard.getColour(), dataCard.getText()));
                }
            }
        }
        gameDeck.setWhiteCards(whiteCards);
        gameDeck.setBlackCards(blackCards);

        return gameDeck;
    }

    /**
     * Gets a DataCard from an id.
     *
     * @param cardId The cardId.
     * @return The corresponding DataCard.
     */
    public static Card getDataCardFromId(int cardId) {
        Optional<Card> cardOptional = Database.getCards().stream().filter(card -> card.getId() == cardId).findFirst();
        return cardOptional.orElse(null);
    }

    /**
     * Gets a DataDeck from a deckName.
     *
     * @param deckName The deckName.
     * @return The corresponding DataDeck.
     */
    public static com.afms.cahgame.data.Deck getDataDeckFromName(String deckName) {
        if (!Database.getDecks().isEmpty()) {
            Optional<com.afms.cahgame.data.Deck> deckOptional = Database.getDecks().stream().filter(deck -> deck.getName().equals(deckName)).findFirst();
            return deckOptional.orElse(null);
        }
        return null;
    }

    /**
     * Gets a random name from the namelist.
     *
     * @return Random name from the namelist.
     */
    public static String getRandomName() {
        return Faker.instance().pokemon().name();
    }

    /**
     * Saves the given name.
     *
     * @param settings SharedPreferences to save the name in.
     * @param newName  The players name.
     */
    public static void saveName(SharedPreferences settings, String newName) {
        SharedPreferences.Editor editor = settings.edit();
        editor.putString("player", newName);
        editor.apply();
    }

    /**
     * Enables god-mode.
     *
     * @param godMode Whether godmode should be activated or not.
     */
    public static void setGodMode(boolean godMode) {
        Util.godMode = godMode;
    }


    /**
     * Creates a deck with all available cards.
     */
    public static void createAllCardsDeck() {
        if (getDataDeckFromName("allcardsdeck") != null) {
            return;
        }
        com.afms.cahgame.data.Deck deck = new com.afms.cahgame.data.Deck("allcardsdeck");
        List<Card> allCards = Database.getCards();
        for (int i = 0; i < allCards.size(); i++) {
            deck.addCard(allCards.get(i).getId());
        }
        Database.addDeck(deck);
    }

    /**
     * Creates the normal CaH cards in the database.
     */
    public static void createStandardCards() {
        // White Cards
        List<Card> cards = new ArrayList<>();
        cards.add(new Card("Being on fire.", Colour.WHITE));
        cards.add(new Card("Racism.", Colour.WHITE));
        cards.add(new Card("Old-people smell.", Colour.WHITE));
        cards.add(new Card("A micropenis.", Colour.WHITE));
        cards.add(new Card("Women in yogurt commercials.", Colour.WHITE));
        cards.add(new Card("Classist undertones.", Colour.WHITE));
        cards.add(new Card("Not giving a shit about the Third World", Colour.WHITE));
        cards.add(new Card("Inserting a mason jar into my anus.", Colour.WHITE));
        cards.add(new Card("Court-ordered rehab.", Colour.WHITE));
        cards.add(new Card("A windmill full of corpses.", Colour.WHITE));
        cards.add(new Card("The gays.", Colour.WHITE));
        cards.add(new Card("An oversized lollipop.", Colour.WHITE));
        cards.add(new Card("African children.", Colour.WHITE));
        cards.add(new Card("An asymmetric boob job.", Colour.WHITE));
        cards.add(new Card("Bingeing and purging.", Colour.WHITE));
        cards.add(new Card("The hardworking Mexican.", Colour.WHITE));
        cards.add(new Card("An Oedipus complex.", Colour.WHITE));
        cards.add(new Card("A tiny horse.", Colour.WHITE));
        cards.add(new Card("Boogers.", Colour.WHITE));
        cards.add(new Card("Penis envy.", Colour.WHITE));
        cards.add(new Card("Barack Obama.", Colour.WHITE));
        cards.add(new Card("My humps.", Colour.WHITE));
        cards.add(new Card("Scientology.", Colour.WHITE));
        cards.add(new Card("Skeletor.", Colour.WHITE));
        cards.add(new Card("Darth Vader.", Colour.WHITE));
        cards.add(new Card("Figgy pudding.", Colour.WHITE));
        cards.add(new Card("Advice from a wise, old black man.", Colour.WHITE));
        cards.add(new Card("Elderly Japanese men.", Colour.WHITE));
        cards.add(new Card("Free samples.", Colour.WHITE));
        cards.add(new Card("Estrogen.", Colour.WHITE));
        cards.add(new Card("Sexual tension.", Colour.WHITE));
        cards.add(new Card("Famine.", Colour.WHITE));
        cards.add(new Card("A stray pube.", Colour.WHITE));
        cards.add(new Card("Men.", Colour.WHITE));
        cards.add(new Card("Heartwarming orphans.", Colour.WHITE));
        cards.add(new Card("Chunks of dead hitchhiker.", Colour.WHITE));
        cards.add(new Card("A bag of magic beans.", Colour.WHITE));
        cards.add(new Card("Repressions.", Colour.WHITE));
        cards.add(new Card("My relationship status.", Colour.WHITE));
        cards.add(new Card("Overcompensation.", Colour.WHITE));
        cards.add(new Card("Peeing a little bit.", Colour.WHITE));
        cards.add(new Card("Pooping back and forth. Forever.", Colour.WHITE));
        cards.add(new Card("A ball of earwax, semen and toenail clippings.", Colour.WHITE));
        cards.add(new Card("Testicular torsion.", Colour.WHITE));
        cards.add(new Card("The Devil himself.", Colour.WHITE));
        cards.add(new Card("The World of Warcraft.", Colour.WHITE));
        cards.add(new Card("MechaHitler.", Colour.WHITE));
        cards.add(new Card("Being fabulous.", Colour.WHITE));
        cards.add(new Card("Pictures of boobs.", Colour.WHITE));
        cards.add(new Card("A gentle caress of the inner thigh.", Colour.WHITE));
        cards.add(new Card("The Amish.", Colour.WHITE));
        cards.add(new Card("The rhythms of Africa.", Colour.WHITE));
        cards.add(new Card("Lance Armstrong's missing testicle.", Colour.WHITE));
        cards.add(new Card("Pedophiles.", Colour.WHITE));
        cards.add(new Card("The Pope.", Colour.WHITE));
        cards.add(new Card("Flying sex snakes.", Colour.WHITE));
        cards.add(new Card("Sexy pillow fights.", Colour.WHITE));
        cards.add(new Card("Invading Poiand.", Colour.WHITE));
        cards.add(new Card("Cybernetic enhancements.", Colour.WHITE));
        cards.add(new Card("Civilian casualties.", Colour.WHITE));
        cards.add(new Card("Jobs.", Colour.WHITE));
        cards.add(new Card("The female orgasm.", Colour.WHITE));
        cards.add(new Card("Bitches.", Colour.WHITE));
        cards.add(new Card("The Boy Scouts of America.", Colour.WHITE));
        cards.add(new Card("Auschwitz.", Colour.WHITE));
        cards.add(new Card("Finger painting.", Colour.WHITE));
        cards.add(new Card("The Care Bear Stare.", Colour.WHITE));
        cards.add(new Card("The Jews.", Colour.WHITE));
        cards.add(new Card("Being marginalized.", Colour.WHITE));
        cards.add(new Card("The Blood of Christ.", Colour.WHITE));
        cards.add(new Card("Dead parents.", Colour.WHITE));
        cards.add(new Card("The art of seduction.", Colour.WHITE));
        cards.add(new Card("Dying of dysentery.", Colour.WHITE));
        cards.add(new Card("Magnets.", Colour.WHITE));
        cards.add(new Card("Jewish fraternities.", Colour.WHITE));
        cards.add(new Card("Natalie Portman.", Colour.WHITE));
        cards.add(new Card("Agriculture.", Colour.WHITE));
        cards.add(new Card("Surprise sex!", Colour.WHITE));
        cards.add(new Card("The homosexual agenda.", Colour.WHITE));
        cards.add(new Card("Robert Downey, Jr.", Colour.WHITE));
        cards.add(new Card("The Trail of Tears.", Colour.WHITE));
        cards.add(new Card("Funky fresh rhymes.", Colour.WHITE));
        cards.add(new Card("The light of a billion suns.", Colour.WHITE));
        cards.add(new Card("Amputees.", Colour.WHITE));
        cards.add(new Card("Throwing a virgin into a volcano.", Colour.WHITE));
        cards.add(new Card("Italians.", Colour.WHITE));
        cards.add(new Card("Explosions.", Colour.WHITE));
        cards.add(new Card("A good sniff.", Colour.WHITE));
        cards.add(new Card("Destroying the evidence.", Colour.WHITE));
        cards.add(new Card("Children on leashes.", Colour.WHITE));
        cards.add(new Card("Catapults.", Colour.WHITE));
        cards.add(new Card("One trillion dollars.", Colour.WHITE));
        cards.add(new Card("Friends with benefits.", Colour.WHITE));
        cards.add(new Card("Dying.", Colour.WHITE));
        cards.add(new Card("Silence.", Colour.WHITE));
        cards.add(new Card("Growing a pair.", Colour.WHITE));
        cards.add(new Card("YOU MUST CONSTRUCT ADDITIONAL PYLONS.", Colour.WHITE));
        cards.add(new Card("Justin Bieber.", Colour.WHITE));
        cards.add(new Card("The Holy Bible.", Colour.WHITE));
        cards.add(new Card("Balls.", Colour.WHITE));
        cards.add(new Card("Praying the gay away.", Colour.WHITE));
        cards.add(new Card("Teenage pregnancy.", Colour.WHITE));
        cards.add(new Card("German dungeon porn.", Colour.WHITE));
        cards.add(new Card("The invisible hand.", Colour.WHITE));
        cards.add(new Card("My inner demons.", Colour.WHITE));
        cards.add(new Card("Powerful thighs.", Colour.WHITE));
        cards.add(new Card("Getting naked and watching Nickelodeon.", Colour.WHITE));
        cards.add(new Card("Crippling debt.", Colour.WHITE));
        cards.add(new Card("Kamikaze pilots.", Colour.WHITE));
        cards.add(new Card("Teaching a robot to love.", Colour.WHITE));
        cards.add(new Card("Police brutality.", Colour.WHITE));
        cards.add(new Card("Horse meat.", Colour.WHITE));
        cards.add(new Card("All-you-can-eat shrimp for $4.99", Colour.WHITE));
        cards.add(new Card("Heteronormativity.", Colour.WHITE));
        cards.add(new Card("Michael Jackson.", Colour.WHITE));
        cards.add(new Card("A really cool hat.", Colour.WHITE));
        cards.add(new Card("Copping a feel.", Colour.WHITE));
        cards.add(new Card("Crystal meth.", Colour.WHITE));
        cards.add(new Card("Shapeshifters.", Colour.WHITE));
        cards.add(new Card("Fingering.", Colour.WHITE));
        cards.add(new Card("A disappointing birthday party.", Colour.WHITE));
        cards.add(new Card("The Patriarchy.", Colour.WHITE));
        cards.add(new Card("My soul.", Colour.WHITE));
        cards.add(new Card("A sausage festival.", Colour.WHITE));
        cards.add(new Card("The chronic.", Colour.WHITE));
        cards.add(new Card("Eugenics.", Colour.WHITE));
        cards.add(new Card("Synergistic management solutions.", Colour.WHITE));
        cards.add(new Card("RoboCop.", Colour.WHITE));
        cards.add(new Card("Stephen Hawking talking dirty.", Colour.WHITE));
        cards.add(new Card("A man on the brink of orgasm.", Colour.WHITE));
        cards.add(new Card("Fiery poops.", Colour.WHITE));
        cards.add(new Card("Public ridicule.", Colour.WHITE));
        cards.add(new Card("White-man scalps.", Colour.WHITE));
        cards.add(new Card("The morbidly obese.", Colour.WHITE));
        cards.add(new Card("Object permanence.", Colour.WHITE));
        cards.add(new Card("Lockjaw.", Colour.WHITE));
        cards.add(new Card("Joe Biden.", Colour.WHITE));
        cards.add(new Card("Bio-engineered assault turtles with acid breath.", Colour.WHITE));
        cards.add(new Card("Wet dreams.", Colour.WHITE));
        cards.add(new Card("Hip hop jewels.", Colour.WHITE));
        cards.add(new Card("Firing a rifle into the air while balls deep into a squealing hog.", Colour.WHITE));
        cards.add(new Card("Panda sex.", Colour.WHITE));
        cards.add(new Card("Necrophilia.", Colour.WHITE));
        cards.add(new Card("Grave robbing.", Colour.WHITE));
        cards.add(new Card("A bleached asshole.", Colour.WHITE));
        cards.add(new Card("Muhammad (Praise Be Unto Him).", Colour.WHITE));
        cards.add(new Card("Multiple stab wounds.", Colour.WHITE));
        cards.add(new Card("Daniel Radcliffe's delicious asshole.", Colour.WHITE));
        cards.add(new Card("A monkey smoking a cigar.", Colour.WHITE));
        cards.add(new Card("Smegma.", Colour.WHITE));
        cards.add(new Card("A live studio audience.", Colour.WHITE));
        cards.add(new Card("The violation of our most basic human rights.", Colour.WHITE));
        cards.add(new Card("Unfathomable stupidity.", Colour.WHITE));
        cards.add(new Card("Sunshine and rainbows.", Colour.WHITE));
        cards.add(new Card("Whipping it out.", Colour.WHITE));
        cards.add(new Card("The token minority.", Colour.WHITE));
        cards.add(new Card("The terrorists.", Colour.WHITE));
        cards.add(new Card("A snapping turtle biting the tip of your penis.", Colour.WHITE));
        cards.add(new Card("Vehicular manslaughter.", Colour.WHITE));
        cards.add(new Card("The Great Depression.", Colour.WHITE));
        cards.add(new Card("Emotions.", Colour.WHITE));
        cards.add(new Card("Getting so angry that you pop a boner.", Colour.WHITE));
        cards.add(new Card("Same-sex ice dancing.", Colour.WHITE));
        cards.add(new Card("An M16 assault rifle.", Colour.WHITE));
        cards.add(new Card("Man meat.", Colour.WHITE));
        cards.add(new Card("Incest.", Colour.WHITE));
        cards.add(new Card("A foul mouth.", Colour.WHITE));
        cards.add(new Card("Flightless birds.", Colour.WHITE));
        cards.add(new Card("Doing the right thing.", Colour.WHITE));
        cards.add(new Card("When you fart and a little bit comes out.", Colour.WHITE));
        cards.add(new Card("Being a dick to children.", Colour.WHITE));
        cards.add(new Card("Poopy diapers.", Colour.WHITE));
        cards.add(new Card("Seeing grandma naked.", Colour.WHITE));
        cards.add(new Card("Raptor attacks.", Colour.WHITE));
        cards.add(new Card("Concealing a boner.", Colour.WHITE));
        cards.add(new Card("Full frontal nudity.", Colour.WHITE));
        cards.add(new Card("Nipple blades.", Colour.WHITE));
        cards.add(new Card("A bitch slap.", Colour.WHITE));
        cards.add(new Card("Michelle Obama's arms.", Colour.WHITE));
        cards.add(new Card("Mouth herpes.", Colour.WHITE));
        cards.add(new Card("A robust mongoloid.", Colour.WHITE));
        cards.add(new Card("Mutually-assured destruction.", Colour.WHITE));
        cards.add(new Card("The Rapture.", Colour.WHITE));
        cards.add(new Card("Road head.", Colour.WHITE));
        cards.add(new Card("Stalin.", Colour.WHITE));
        cards.add(new Card("Lactation.", Colour.WHITE));
        cards.add(new Card("The true meaning of Christmas.", Colour.WHITE));
        cards.add(new Card("Self-loathing.", Colour.WHITE));
        cards.add(new Card("A brain tumor.", Colour.WHITE));
        cards.add(new Card("Dead babies.", Colour.WHITE));
        cards.add(new Card("New Age music.", Colour.WHITE));
        cards.add(new Card("A thermonuclear detonation.", Colour.WHITE));
        cards.add(new Card("Geese.", Colour.WHITE));
        cards.add(new Card("Kanye West.", Colour.WHITE));
        cards.add(new Card("God.", Colour.WHITE));
        cards.add(new Card("A spastic nerd.", Colour.WHITE));
        cards.add(new Card("Harry Potter erotica.", Colour.WHITE));
        cards.add(new Card("Kids with ass cancer.", Colour.WHITE));
        cards.add(new Card("Lumberjack fantasies.", Colour.WHITE));
        cards.add(new Card("The American Dream.", Colour.WHITE));
        cards.add(new Card("Puberty.", Colour.WHITE));
        cards.add(new Card("Sweet, sweet vengeance.", Colour.WHITE));
        cards.add(new Card("Winking at old people.", Colour.WHITE));
        cards.add(new Card("The wonders of the Orient.", Colour.WHITE));
        cards.add(new Card("Oompa-Loompas.", Colour.WHITE));
        cards.add(new Card("Authentic Mexican cuisine.", Colour.WHITE));
        cards.add(new Card("Preteens.", Colour.WHITE));
        cards.add(new Card("The Little Engine That Could.", Colour.WHITE));
        cards.add(new Card("A Fleshlight.", Colour.WHITE));
        cards.add(new Card("Erectile dysfunction.", Colour.WHITE));
        cards.add(new Card("Having anuses for eyes.", Colour.WHITE));
        cards.add(new Card("Saxophone solos.", Colour.WHITE));
        cards.add(new Card("Land mines.", Colour.WHITE));
        cards.add(new Card("Running out of semen.", Colour.WHITE));
        cards.add(new Card("Me time.", Colour.WHITE));
        cards.add(new Card("Nickelback.", Colour.WHITE));
        cards.add(new Card("Vigilante justice.", Colour.WHITE));
        cards.add(new Card("The South.", Colour.WHITE));
        cards.add(new Card("Opposable thumbs.", Colour.WHITE));
        cards.add(new Card("Ghosts.", Colour.WHITE));
        cards.add(new Card("Alcoholism.", Colour.WHITE));
        cards.add(new Card("Poorly-timed Holocaust jokes.", Colour.WHITE));
        cards.add(new Card("Inappropriate yodeling.", Colour.WHITE));
        cards.add(new Card("Battlefield amputations.", Colour.WHITE));
        cards.add(new Card("Exactly what you'd expect.", Colour.WHITE));
        cards.add(new Card("A time travel paradox.", Colour.WHITE));
        cards.add(new Card("AXE Body Spray.", Colour.WHITE));
        cards.add(new Card("The pirate's life.", Colour.WHITE));
        cards.add(new Card("Saying 'I love you.'", Colour.WHITE));
        cards.add(new Card("A sassy black woman.", Colour.WHITE));
        cards.add(new Card("Being a motherfucking sorcerer.", Colour.WHITE));
        cards.add(new Card("A mopey zoo lion.", Colour.WHITE));
        cards.add(new Card("A falcon with a cap on its head.", Colour.WHITE));
        cards.add(new Card("Farting and walking away.", Colour.WHITE));
        cards.add(new Card("A mating display.", Colour.WHITE));
        cards.add(new Card("The Chinese gymnastics team.", Colour.WHITE));
        cards.add(new Card("Friction.", Colour.WHITE));
        cards.add(new Card("Asians who aren't good at math.", Colour.WHITE));
        cards.add(new Card("Fear itself.", Colour.WHITE));
        cards.add(new Card("A can of whoop-ass.", Colour.WHITE));
        cards.add(new Card("Licking things to claim them as your own.", Colour.WHITE));
        cards.add(new Card("Vikings.", Colour.WHITE));
        cards.add(new Card("Hot cheese.", Colour.WHITE));
        cards.add(new Card("Nicolas Cage.", Colour.WHITE));
        cards.add(new Card("A defective condom.", Colour.WHITE));
        cards.add(new Card("The inevitable heat death of the universe.", Colour.WHITE));
        cards.add(new Card("Republicans.", Colour.WHITE));
        cards.add(new Card("William Shatner.", Colour.WHITE));
        cards.add(new Card("Tentacle porn.", Colour.WHITE));
        cards.add(new Card("Sperm whales.", Colour.WHITE));
        cards.add(new Card("Lady Gaga.", Colour.WHITE));
        cards.add(new Card("The wrath of Vladimir Putin.", Colour.WHITE));
        cards.add(new Card("Gloryholes.", Colour.WHITE));
        cards.add(new Card("Daddy issues.", Colour.WHITE));
        cards.add(new Card("A mime having a stroke.", Colour.WHITE));
        cards.add(new Card("White people.", Colour.WHITE));
        cards.add(new Card("A lifetime of sadness.", Colour.WHITE));
        cards.add(new Card("Tasteful sideboob.", Colour.WHITE));
        cards.add(new Card("Nazis.", Colour.WHITE));
        cards.add(new Card("A cooler full of organs.", Colour.WHITE));
        cards.add(new Card("Giving 110%.", Colour.WHITE));
        cards.add(new Card("Doin' it in the butt.", Colour.WHITE));
        cards.add(new Card("Holding down a child and farting all over him.", Colour.WHITE));
        cards.add(new Card("A homoerotic volleyball montage.", Colour.WHITE));
        cards.add(new Card("Puppies!", Colour.WHITE));
        cards.add(new Card("Nature male enhancement.", Colour.WHITE));
        cards.add(new Card("Brown people.", Colour.WHITE));
        cards.add(new Card("Dropping a chandelier on your enemies and riding the rope up.", Colour.WHITE));
        cards.add(new Card("Soup that is too hot.", Colour.WHITE));
        cards.add(new Card("Sex with Patrick Stewart.", Colour.WHITE));
        cards.add(new Card("Hormone injections.", Colour.WHITE));
        cards.add(new Card("Pulling out.", Colour.WHITE));
        cards.add(new Card("The Big Bang.", Colour.WHITE));
        cards.add(new Card("Giving birth to the Antichrist.", Colour.WHITE));
        cards.add(new Card("Dark and mysterious forces beyong our control.", Colour.WHITE));
        cards.add(new Card("Count Chocula.", Colour.WHITE));
        cards.add(new Card("The Hamburglar.", Colour.WHITE));
        cards.add(new Card("Not reciprocating oral sex.", Colour.WHITE));
        cards.add(new Card("Hot people.", Colour.WHITE));
        cards.add(new Card("Foreskin.", Colour.WHITE));
        cards.add(new Card("Assless chaps.", Colour.WHITE));
        cards.add(new Card("The miracle of childbirth.", Colour.WHITE));
        cards.add(new Card("Waiting 'til marriage.", Colour.WHITE));
        cards.add(new Card("Two midgets shitting into a bucket.", Colour.WHITE));
        cards.add(new Card("A sad handjob.", Colour.WHITE));
        cards.add(new Card("Cheating in the Special Olympics.", Colour.WHITE));
        cards.add(new Card("Miley Cirus at 55.", Colour.WHITE));
        cards.add(new Card("Our first chimpanzee president.", Colour.WHITE));
        cards.add(new Card("Extremely tight pants.", Colour.WHITE));
        cards.add(new Card("Third base.", Colour.WHITE));
        cards.add(new Card("Waking up half-naked in a Denny's parking lot.", Colour.WHITE));
        cards.add(new Card("White priilege.", Colour.WHITE));
        cards.add(new Card("Hope.", Colour.WHITE));
        cards.add(new Card("Taking off your shirt.", Colour.WHITE));
        cards.add(new Card("Ethnic cleansing.", Colour.WHITE));
        cards.add(new Card("Getting really high.", Colour.WHITE));
        cards.add(new Card("Natural selection.", Colour.WHITE));
        cards.add(new Card("A gassy antelope.", Colour.WHITE));
        cards.add(new Card("My sex life.", Colour.WHITE));
        cards.add(new Card("Pretending to care.", Colour.WHITE));
        cards.add(new Card("My black ass.", Colour.WHITE));
        cards.add(new Card("BATMAN!!!", Colour.WHITE));
        cards.add(new Card("Homeless people.", Colour.WHITE));
        cards.add(new Card("Racially-biased SAT questions.", Colour.WHITE));
        cards.add(new Card("Centaurs.", Colour.WHITE));
        cards.add(new Card("A salty surprise.", Colour.WHITE));
        cards.add(new Card("72 virgins.", Colour.WHITE));
        cards.add(new Card("Pixelated bukkake.", Colour.WHITE));
        cards.add(new Card("Seppuku.", Colour.WHITE));
        cards.add(new Card("Mestrual rage.", Colour.WHITE));
        cards.add(new Card("Sexual peeing.", Colour.WHITE));
        cards.add(new Card("An endless tream of diarrhea.", Colour.WHITE));
        cards.add(new Card("Horrifiyng laser hair removal accidents.", Colour.WHITE));
        cards.add(new Card("A fetus.", Colour.WHITE));
        cards.add(new Card("Riding off into the sunset.", Colour.WHITE));
        cards.add(new Card("Goblins.", Colour.WHITE));
        cards.add(new Card("Eating the last known bison.", Colour.WHITE));
        cards.add(new Card("Shiny objects.", Colour.WHITE));
        cards.add(new Card("Being rich.", Colour.WHITE));
        cards.add(new Card("World peace.", Colour.WHITE));
        cards.add(new Card("Dick fingers.", Colour.WHITE));
        cards.add(new Card("Chainsaws for hands.", Colour.WHITE));
        cards.add(new Card("Penis breath.", Colour.WHITE));
        cards.add(new Card("Laying an egg.", Colour.WHITE));
        cards.add(new Card("My genitals.", Colour.WHITE));
        cards.add(new Card("Grandma.", Colour.WHITE));
        cards.add(new Card("Flesh-eating bacteria.", Colour.WHITE));
        cards.add(new Card("Poor people.", Colour.WHITE));
        cards.add(new Card("50,000 volts straight to the nipples.", Colour.WHITE));
        cards.add(new Card("The Übermensch.", Colour.WHITE));
        cards.add(new Card("Poor life choices.", Colour.WHITE));
        cards.add(new Card("Altar boys.", Colour.WHITE));
        cards.add(new Card("My vagina.", Colour.WHITE));
        cards.add(new Card("Pac-Man uncontrollably guzzling cum.", Colour.WHITE));
        cards.add(new Card("Sniffing glue.", Colour.WHITE));
        cards.add(new Card("The placenta.", Colour.WHITE));
        cards.add(new Card("Spontaneous human combustion.", Colour.WHITE));
        cards.add(new Card("The KKK.", Colour.WHITE));
        cards.add(new Card("The clitoris.", Colour.WHITE));
        cards.add(new Card("Not wearing pants.", Colour.WHITE));
        cards.add(new Card("Consensual sex.", Colour.WHITE));
        cards.add(new Card("Black people.", Colour.WHITE));
        cards.add(new Card("A bucket of fish heads.", Colour.WHITE));
        cards.add(new Card("Passive-agrressive Post-it notes.", Colour.WHITE));
        cards.add(new Card("The heart of a child.", Colour.WHITE));
        cards.add(new Card("Crumbs all over the god damn carpet.", Colour.WHITE));
        cards.add(new Card("Being fat and stupid.", Colour.WHITE));
        cards.add(new Card("Getting married, having a few kids, buying some stuff, retiring to Florida, and dying.", Colour.WHITE));
        cards.add(new Card("Sean Connery.", Colour.WHITE));
        cards.add(new Card("Expecting to burp and vomiting on the floor.", Colour.WHITE));
        cards.add(new Card("Wifely duties.", Colour.WHITE));
        cards.add(new Card("A pyramid of severed heads.", Colour.WHITE));
        cards.add(new Card("Genghis Khan.", Colour.WHITE));
        cards.add(new Card("Crucifixion.", Colour.WHITE));
        cards.add(new Card("Friendly fire.", Colour.WHITE));
        cards.add(new Card("AIDS.", Colour.WHITE));
        cards.add(new Card("8 oz. of sweet Mexican black-tar heroin.", Colour.WHITE));
        cards.add(new Card("Half-assed foreplay.", Colour.WHITE));
        cards.add(new Card("Edible underpants.", Colour.WHITE));
        cards.add(new Card("My collection of high-tech sex toys.", Colour.WHITE));
        cards.add(new Card("The Force.", Colour.WHITE));
        cards.add(new Card("Bees?", Colour.WHITE));
        cards.add(new Card("Some god-damn peace and quiet.", Colour.WHITE));
        cards.add(new Card("Jerking off into a pool of children's tears.", Colour.WHITE));
        cards.add(new Card("A micropig wearing a tiny raincoat and booties.", Colour.WHITE));
        cards.add(new Card("Three dicks at the same time.", Colour.WHITE));
        cards.add(new Card("Masturbation.", Colour.WHITE));
        cards.add(new Card("Tom Cruise.", Colour.WHITE));
        cards.add(new Card("Anal beads.", Colour.WHITE));
        cards.add(new Card("Drinking alone.", Colour.WHITE));
        cards.add(new Card("Cards Against Humankind.", Colour.WHITE));
        cards.add(new Card("Coat hanger abortions.", Colour.WHITE));
        cards.add(new Card("Used panties.", Colour.WHITE));
        cards.add(new Card("Cuddling.", Colour.WHITE));
        cards.add(new Card("Wiping her butt.", Colour.WHITE));
        cards.add(new Card("Morgan Freeman's voice.", Colour.WHITE));
        cards.add(new Card("A middle-aged man on roller skates.", Colour.WHITE));
        cards.add(new Card("Gandhi.", Colour.WHITE));
        cards.add(new Card("Keanu Reeves.", Colour.WHITE));
        cards.add(new Card("Child beauty pageants.", Colour.WHITE));
        cards.add(new Card("Child abuse.", Colour.WHITE));
        cards.add(new Card("Bill Nye the Science Guy.", Colour.WHITE));
        cards.add(new Card("Science.", Colour.WHITE));
        cards.add(new Card("A tribe of warrior women.", Colour.WHITE));
        cards.add(new Card("Viagra.", Colour.WHITE));
        cards.add(new Card("Her Majesty, Queen Elizabeth II.", Colour.WHITE));
        cards.add(new Card("The entire Mormon Tabernacle Choir.", Colour.WHITE));
        cards.add(new Card("This year's mass shooting.", Colour.WHITE));
        cards.add(new Card("An erection that lasts longer than four hours.", Colour.WHITE));
        cards.add(new Card("Dead Jews.", Colour.WHITE));

        cards.add(new Card("How did I lose my virginity.", Colour.BLACK));
        cards.add(new Card("Why can't I sleep at night?", Colour.BLACK));
        cards.add(new Card("What's that smell?", Colour.BLACK));
        cards.add(new Card("I got 99 problems but __________ ain't one.", Colour.BLACK));
        cards.add(new Card("Maybe she's born with it. Maybe it's _________.", Colour.BLACK));
        cards.add(new Card("What's the next Happy Meal toy?", Colour.BLACK));
        cards.add(new Card("Here is the church. Here is the steeple. Open the doors and there is ________.", Colour.BLACK));
        cards.add(new Card("It's a pity that kids these days are all getting involved with _________.", Colour.BLACK));
        cards.add(new Card("Today on Maury: 'Help! My son is _______!'", Colour.BLACK));
        cards.add(new Card("Alternative medicine is now embracing the curative powers of __________.", Colour.BLACK));
        cards.add(new Card("What's that sound?", Colour.BLACK));
        cards.add(new Card("What ended my last relationship?", Colour.BLACK));
        cards.add(new Card("MTV's new reality show features eight washed-up celebreties living with ________.", Colour.BLACK));
        cards.add(new Card("I drink to forget ________.", Colour.BLACK));
        cards.add(new Card("I'm sorry Professor, but I couldn't complete my homework because of ________.", Colour.BLACK));
        cards.add(new Card("What is Batman's guilty pleasure?", Colour.BLACK));
        cards.add(new Card("The world will end with _________.", Colour.BLACK));
        cards.add(new Card("What's a girl's best friend.", Colour.BLACK));
        cards.add(new Card("TSA guidelines now prohibit __________ on airplanes.", Colour.BLACK));
        cards.add(new Card("__________. That's how I want to die.", Colour.BLACK));
        cards.add(new Card("I get by with a little help from ________.", Colour.BLACK));
        cards.add(new Card("Dear Abby, I'm having some trouble with _______ and would like your advice,", Colour.BLACK));
        cards.add(new Card("Instead of coal, Santa now give the bad children ________.", Colour.BLACK));
        cards.add(new Card("What's the most emo?", Colour.BLACK));
        cards.add(new Card("In 1000 years, when paper money is a distant memory, how will we pay for goods and services?", Colour.BLACK));
        cards.add(new Card("A romantic candlelight dinner would be incomplete without _________.", Colour.BLACK));
        cards.add(new Card("White people like ________.", Colour.BLACK));
        cards.add(new Card("____________! High five, bro.", Colour.BLACK));
        cards.add(new Card("Next from J.K. Rowling: Harry Potter and the Chamber of __________.", Colour.BLACK));
        cards.add(new Card("Introcucing Xtreme Baseball! It's like baseball, but with _________!", Colour.BLACK));
        cards.add(new Card("War! What is it good for?", Colour.BLACK));
        cards.add(new Card("During sex, I like to think about _________.", Colour.BLACK));
        cards.add(new Card("What are my parents hiding from me?", Colour.BLACK));
        cards.add(new Card("What will always get you laid?", Colour.BLACK));
        cards.add(new Card("In L.A. County Jail, word is you can trade 200 cigarettes for _________.", Colour.BLACK));
        cards.add(new Card("What did I bring back from Mexico?", Colour.BLACK));
        cards.add(new Card("What don't you want to find in your Kung Pao chicken?", Colour.BLACK));
        cards.add(new Card("What will I bring back in time to convince people that I am a powerful wizard?", Colour.BLACK));
        cards.add(new Card("How am I maintaining my relationship status?", Colour.BLACK));
        cards.add(new Card("_____________. It's a trap!", Colour.BLACK));
        cards.add(new Card("Coming to Broadway this season: ___________: The Musical.", Colour.BLACK));
        cards.add(new Card("After the earthquake, Sean Penn brought ___________ to the people of Haiti.", Colour.BLACK));
        cards.add(new Card("Next on ESPN2, the World Series of _________.", Colour.BLACK));
        cards.add(new Card("Bug before I kill you, Mr. Bond, I must show you __________.", Colour.BLACK));
        cards.add(new Card("What gives me uncontrollable gas?", Colour.BLACK));
        cards.add(new Card("The class field trip was completely ruined by __________.", Colour.BLACK));
        cards.add(new Card("When Pharaoh remained unmoved, Moses called down a Plague of __________.", Colour.BLACK));
        cards.add(new Card("What's my secret power?", Colour.BLACK));
        cards.add(new Card("What's there a ton of in heaven?", Colour.BLACK));
        cards.add(new Card("What would grandma find disturbing, yet oddly charming?", Colour.BLACK));
        cards.add(new Card("What did the U.S. airdrop to the children Afghanistan?", Colour.BLACK));
        cards.add(new Card("What helps Obama unwind?", Colour.BLACK));
        cards.add(new Card("What did Vin Diesel eat for dinner?", Colour.BLACK));
        cards.add(new Card("_________: good to the last drop.", Colour.BLACK));
        cards.add(new Card("Why am I sticky?", Colour.BLACK));
        cards.add(new Card("What gets better with age?", Colour.BLACK));
        cards.add(new Card("________: kid-tested, mother approved.", Colour.BLACK));
        cards.add(new Card("Daddy, why is mommy crying?", Colour.BLACK));
        cards.add(new Card("Life for American Indians was forever changed  when the White Man introduced them to ________.", Colour.BLACK));
        cards.add(new Card("I don't know with what weapons World War 3 will be fought, but World War 4 will be fought with _______.", Colour.BLACK));
        cards.add(new Card("What am I giving up for Lent?", Colour.BLACK));
        cards.add(new Card("What's Donald Trump thinking about right now?", Colour.BLACK));
        cards.add(new Card("The Smithsonian Museum of Natural History has just opened an interactive exhibit on _________.", Colour.BLACK));
        cards.add(new Card("When I cam President of the U.S., I will create the Department of _________.", Colour.BLACK));
        cards.add(new Card("When I'm a billionaire, I shall erect a 50-foot statue to commemorate ________.", Colour.BLACK));
        cards.add(new Card("What's my anti-drug?", Colour.BLACK));
        cards.add(new Card("What never fails to liven up the party?", Colour.BLACK));
        cards.add(new Card("What's that new diet?", Colour.BLACK));
        cards.add(new Card("Fun tip! When your man asks you to go down on him, try surprising him with _______ instead.", Colour.BLACK));

        Database.addNewCards(cards);
    }

    private static Deck get_lucas_deck(){
        Deck lucas_deck = new Deck();
        lucas_deck.setName("German #2");
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Alles ist besser mit ___."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Warum tut mir alles weh?"));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Wegen eines PR-Debakels bietet Aldi nun nicht mehr ___ an."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Meine Lebensphilosophie: ___."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Im siebten Kreis der Hölle müssen die Sünder ___ für alle Ewigkeit ertragen."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Für mehr ___ in der Öffentlichkeit!"));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "IS verspricht Selbstmordattentätern neuerdings ___ statt 72 Jungfrauen."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Ich mochte ___, bevor es cool war."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "___: Toll in der Theorie, ein ziemliches Durcheinander in der Praxis."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Dank ___ hatte ich ein verlängertes Wochenende."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "In ihrem neuen Kinofilm schlägt sich die Eisprinzessin Elsa das erste Mal mit ___ herum."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Mein Plan für die Weltherrschaft beginnt mit ___."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Beim Sex denke ich gerne an ___."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Was ist Liebe ohne ___?"));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Was brachte die Orgie zu einem schlagartigen Stillstand?"));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "___ ist was Frauen wollen."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Ich habe auf die harte Tour gelernt, dass man einen trauernden Freund nicht mit ___ aufheitern kann."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Woher kommt der Fleck auf meiner Couch?"));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "___ – gefürchtet mit 5, begehrt mit 18."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Ich trinke, um ___ zu vergessen."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Am achten Tag erschuf Gott ___. Er ist seitdem nicht mehr gesehen worden."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Wie kompensiere ich für meinen winzigen Penis?"));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Dank ___ halte ich meine Beziehung am Laufen."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "___ – da muss ich an deine Mutter denken."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "___ ruiniert unser Land."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "In seiner Oster-Ansprache betonte der Papst die Wichtigkeit von ___ als christlichem Wert."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Die AfD fordert in ihrem Wahlprogramm mehr ___ für Deutsche."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Ich liebe den Geruch von ___ am Morgen."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "___– furchtbare Tragödie oder sexuelle Gelegenheit?"));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Wir haben nichts zu fürchten außer ___ an sich."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Was hat zum Ende meiner letzten Beziehung geführt?"));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Für was hältst du mich eigentlich?"));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Um mehr Besucher anzulocken, hat das Deutsche Museum eine interaktive Ausstellung über ___ eröffnet."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Papa, warum weint Mama?"));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Statt Kohle gibt der Weihnachtsmann bösen Kindern nun ___."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "In einem Tweet hat Donald Trump ___ für sein Versagen verantwortlich gemacht."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Ich habe letzte Nacht fünf Stunden mit Internettrollen über ___ gestritten."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Ein Leben ohne ___ist möglich, aber sinnlos."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Um sein Land wieder unter Kontrolle zu bringen, setzt Assad auf ___."));
        lucas_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Angela Merkel hat ___ zur Chefsache erklärt."));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein gebleichtes Arschloch"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein Mikropenis"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein Hirntumor"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Meine Genitalien"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Resteficken"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Weihnachtsbescherung im Kinderheim"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Sonnenschein und Regenbögen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Second-Hand-Sexshop"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Eurovision Song Contest"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Islamisierung des Abendlandes"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Mein Browserverlauf"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Postnatale Abtreibung"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Omas Pornokiste"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Gleichgeschlechtlicher Eiskunstlauf"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "50 Shades of Grey"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Die Kommentare auf RT Deutsch "));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Brustmilch-Eiscreme"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Donald Trumps Toupet"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Gruppensex in der Demenzklinik"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Deiner Partnerin einen Dreier mit ihrer Mutter vorschlagen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein epileptischer Anfall bei der Bombenentschärfung"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Verschwörungstheorien"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "1.000 schottische Krieger, die gleichzeitig ihre Kilts angeben"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Männer im String-Tanga auf dem Kinderspielplatz"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Tränengas im Kindergarten"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Bibel-Fanfiction"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Brexit"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "RTL 2"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Zombie-Clowns"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein dicker Mann mittleren Alters in einem zu kleinen Sailor-Moon-Kostüm"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Minions"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Horst Seehofer"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Freunde mit einer Skimaske und Kettensäge überraschen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Frauenwahlrecht"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Schluss machen per Twitter"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Natursekt"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Deine Mudda"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "FC Bayern-Fans"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Die genetische Verbesserung der Menschheit"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ethnische Säuberung"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Katzenbabys"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Mädels vor der Abtreibungsklinik aufreißen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Netflix"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Klitoris"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Stephen Hawking, wenn er schmutzige Sachen sagt"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Penispropeller"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Kackende Frauen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Eine gewaxte Vagina"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Meine Sexspielzeugsammlung"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Frauen am Steuer"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Genitalherpes"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Jesus"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Katapulte"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Einen Orgasmus vortäuschen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Pornodarsteller"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Blackjack und Nutten"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Osteuropäische Volksmusik"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Wichsvorlagen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Etwas anlecken, um es zu markieren"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Polizeigewalt"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Impotenz"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Männliche Rückenbehaarung"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Eine Erektion, die mehrere Stunden anhält"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Penisneid"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Sex im Fahrstuhl"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Sharknado"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein toter Anhalter im Kofferraum"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Politische Flüchtlinge"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Chemische Kastration"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Geschichtsrevisionismus"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Der Nationalsozialistische Untergrund"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Bahnhofsklatscher"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Eine Kühltasche voller Organe"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein Swingerclub mit Kinderbetreuung"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Zwei Zwerge, die zusammen in einen Eimer scheißen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Gebrauchte Damenunterwäsche aus dem Automaten"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Sich den Arsch mit 100-Euro-Scheinen abwischen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Grammatiknazi mit Legasthenie"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Das Vierte Reich"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Eispickel-Lobotomie"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein unerfülltes Sexleben"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Furchtbar kitschige Pärchen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Genmanipulierte Angriffsschildkröten mit Säureatem"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Bambis Mutter"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein 30 cm langer Penis"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Kannibalinnen im Avocadodschungel des Todes"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Schimpansen mit mangelnder Selbstbeherrschung"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Chilisoße als Gleitgel verwenden"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Muttertag"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Einem Kind Süßigkeiten wegnehmen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein Kondom ausleihen und gebraucht zurückgeben"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Intravenöse Koffeinzufuhr"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Wikipedia bearbeiten, um einen Streit zu gewinnen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Sich nackt ausziehen und den Kinderkanal ansehen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Die Verletzung grundlegender Menschenrechte"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Die Alternative für Deutschland"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Versehentlich eine Sexnachricht an deine Mutter schicken"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Japanische Schulmädchen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Autokannibalismus"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Gutmenschen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Neonazis im Dönerladen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Germany's next Topmodel"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Chemtrails"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Eine furzende Antilope"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Kampfjetpiloten mit Narkolepsie"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Vladimir Putins Obenohne-Fotos"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein Hello-Kitty-Vibrator"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Pummeleinhorn"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Fake News"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Software-Absturz im Herzschrittmacher"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Der NPD-Chef, wie er von Zombies zerfleischt wird"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Das Oktoberfest"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Verpflichtende Homo-Ehe"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Deinem Haustier beim Sex zusehen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Hormonstau"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Regel Nr.34"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Der Liebhaber deiner Mutter "));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Der weibliche Orgasmus"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Das Safeword vergessen "));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Es von hinten besorgt bekommen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Einen Haufen im Bällebad hinterlassen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Den Spieleabend zu einer Sex-Orgie ausarten lassen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Obszöne Yogaposen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Christliche Werte "));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Axe Body Spray "));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Candle-Light-Dinner im Schlossgarten"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Grumpy Cat"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Von Disney inspirierte Pornografie"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Weihnachtsplätzchen mit Knoblauch und Tabasco"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Sexuell anzügliche Weihnachtsdekoration"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Masernpartys"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Moderate Faschisten"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Beatrix von Storch"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Wirtschaftsflüchtlinge"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Russische Regierungskritiker"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Niveaulimbo"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Mein Sexleben"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Facebook"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Pubertierende Mädchen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Kinderschönheitswettbewerbe"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ahnungsloses Fingern"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Schwanzwedeln"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Unterwäsche auf links tragen, um nicht waschen zu müssen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Pokemon Go"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Eine arschfreie Cowboyhose"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Bilder von Titten"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Einen Ständen kaschieren"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Eigenurin-Behandlungen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Halbherziges Vorspiel"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Penispumpen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Zweckentfremdetes Stangengemüse"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Kondome mit Geschmack"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Das bedingungslose Grundeinkommen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Tierbefreiung im Seuchenlabor"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Aufgewärmter, vier Tage alter Kaffee"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Biologische Kampfstoffe"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Die Kinder in der Badewanne ertränken"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Der massive Penis von King Kong"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Haschkekse auf dem Kirchenpicknick"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein Leck in der Gasleitung"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Fleshlight"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Hochzeiten mit Disneymotiv"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Frauen in Joghurt-Werbespots"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein zartes Streicheln der Oberschenkel-Innenseite"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Friends with Benefits"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Fanatische Nickelback-Fans"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Passiv-aggressive Post-It-Notizen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein Niesfetisch"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein kuschelbedürftiger Grizzly"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Cards against Humankind"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Magic Mushrooms"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Eine Alkoholvergiftung"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Die Bild-Zeitung"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Kostenlose Süßigkeiten von Fremden "));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Die deutsche Bahn"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "YouTube"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Spongebob Schwammkopf"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Neil Patrick Harris"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Die Augsburger Puppenkiste"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Origami Sexspielzeug"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "In die Badewannne scheißen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Gesichtsmalerei mit Permanentfarben"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Die Tränen eines Clowns"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Die zerschmetterten Träume einer Stripperin"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein Einlauf mit Mentos und Cola"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Eltern wegen ihres weinenden Babys an den Pranger stellen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Die schwarze Seele von Markus Söder"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Riesige mutierte Kakerlaken"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Gerhard Schröder"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Helmut Kohl"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Angela Merkel"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Sich einscheißen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Genitalläuse"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Meine heiße Cousine"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein Moment der Stille"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Borat"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Die Matrix"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Recep Tayyip Erdogan"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein vernachlässigtes Tamagotchi"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Chuck Norris"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein mit Katzenpisse geladener Supersoaker"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Eheliche Pflichten"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Hipster mit ihren iPhones"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Mohandas \"Mahatma\" Gandhi"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Dessous von KiK"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Analpolonaise"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "nananana BATMAN!!!"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Um drei Uhr morgens nackt Parkour laufen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Tentacle Porn"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Eine Jungfrau in einen Vulkan werfen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Maximalpigmentierte Mitbürger "));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Elektroschock-Therapie"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Arschgeweihe"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Nymphomaninnen"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ein Handjob in der U-Bahn"));
        lucas_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Essbare Unterwäsche"));
        return lucas_deck;
    }

    private static Deck get_pia_deck(){
        Deck pia_deck = new Deck();
        pia_deck.setName("German #1");
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Vielleicht wurde sie damit gebore vielleicht is es ____."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Es heißt in der JVA Tegel kannst du 200 Zigaretten für ____ eintauschen."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Was ist am meisten emo?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Warum tut mein Arsch so weh?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Letzte Nacht träumte ich von ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Was hat das Internet heute zu bieten?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Die magischen Kräfte des Mondes bescheren uns heute Nacht ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Morgens größer als Abends:"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Mein Geheimnis wie ich so viel Gewicht verloren hab ist ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Was würde Jesus glücklich machen?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Mein Lieblingsduft ist ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "___! Spaß für die ganze Familie!"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Wie nennt sie deinen Schwanz?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Es gab einen riesigen Skandal, als Frau Hübner den Kindergartenkindern ___ gezeigt hat."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "In der nächsten Folge muss Sherlock Holmes das Geheimnis um ___ lüften."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "___ is besser in Japan."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Kann ich bitte mehr ___ haben?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Laut Mama ist das beste Mittel gegen Kater ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Nichts auf der Welt ist so schlimm wie ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Unsere beste Waffe in der Zombie Apokalypse ist ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Was würde Oma verstören und auch ein bisschen anziehen?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Hier liegt Friedrich Schäfer, 1982-2016. Er starb wegen ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Woher kommt der Fleck auf meinem Bettlaken?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Letztens bei der Mutter hatten wir ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Wieso juckt es zwischen meinen Arschbacken?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Was war das letzte, wonach ich gegoogled habe?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Wodurch hast du deine Unschuld verloren?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Schwarze Menschen sind wie ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Mama, Papa, das ist ___ und ich bin total verliebt."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Das Volk verlangt nach ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "___ ist eine Metapher für die Liebe."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Der Vatikan hat vor Kurzem verlauten lassen, dass ___ keine Sünde mehr ist."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Die Mafia hinterließ mir ___ als Warnung."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "In Wahrheit entstehen Altersflecken durch ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Als ich letztens nach dem Scheißen in die Schüssel sah, lag dort ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Die Alternativmedizin bedient sich nun den heilsamen Kräften von ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Was wird im Alter besser?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Die Klassenfahrt wurde durch ___ völlig ruiniert."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Was ist Batmans heimliches Laster?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Im Profi-Baseball wurde ___ verboten, weil es Spielern unfaire Vorteile verschaffte."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "In 1.000 Jahren, wenn Papiergeld nur eine entfernte Erinnerung ist, wird ___ unsere Währung sein."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Ein neuer Tag, ein neuer ___!"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Ich fühle mich schön mit ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Zum Scheuern und Putzen nur ___ benutzen."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Ist ___ auch ein Instrument?"));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "___ aktiviert Abwehrkräfte."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Nichts geht über ___."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "Zukunft wird aus ___ gemacht."));
        pia_deck.addBlackCard(new com.afms.cahgame.game.Card(Colour.BLACK, "___ ist der Anfang von allem."));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Pupertät"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Charisma"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Schwarze"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Weiße"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Darth Vader"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Pummeluff"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Mehl"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Hemmungsloses Nageln"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Atomkrieg"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Fettleibigkeit"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "liebevoller Geschwistersex"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Sahnesteif"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Organhandel"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Kevin"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "das Blut einer Meerjungfrau"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "U-Bahnfahrten"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "in eine Decke Brüllen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Gottes Zorn"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Polizeigewalt"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Hitlers Gasrechnung"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein \"Fick dich!\""));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "20 Fünfjährige"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "spontane menschliche Entzündung"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Windows 95"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Flüssigkleber als Gleitgel verwenden"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "russische Kellerpornos"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Titanen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "fettfreie Butter"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "das Meer?"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "öffentliches BDSM"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein Einhorn mit AIDS"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "stolpern und versehentlich einen Hooligan schubsen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "50 Shades of GAAAAYYY!"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "das Sexleben vom Papst"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Facbook"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "eine Ananas auskacken"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "zu spät bemerken, dass der Klodeckel unten ist"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Deutschtürken"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Blowjobs für Jesus"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Angela Merkels Lächeln"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "der mumifizierte Schwanz von Napoleon Bonaparte"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein Tumor mit Zähnen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "drei Eier"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "eine Mikrowelle zur Abtreibung verwenden"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Rainbow Road"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Impfgegner, die an Masern sterben"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Holocaust"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Beliebers"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Arschpickel ausdrücken"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "nach dem Masturbieren an den Fingern riechen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "über Krebs lachen und später an Krebs sterben"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein großes Glas cremige Erdnussbutter"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Kim Kardashian"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein Amoklauf"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Menschenhandel"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "meine funkelnde Vagina"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "einem Vegetarier heimlich Fleisch ins Essen mischen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Vodka in Wasserflaschen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Bälle, die heftig im Wind wehen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "peinliches Schweigen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein Mund voll mit etwas von dem ich hoffe dass es Käse ist"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Hasch-Kekse für den Weihnachtsmann hinlegen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "passiv-aggressive Haustiere"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Melanie Trump"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "überfüllte Kondome"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "kleine Elefanten"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "zu viele Pinguine"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "IS Gay Pride"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Tierporno"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Kühe"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "wie Lachs riechen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "aus einem Autofenster kacken"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Super Mario"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Kindern beibringen zu fluchen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "eine Mango unsittlich berühren"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Apple"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Samsung"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Microsoft"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Veganismus"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Einhorn-Sperma"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Schnaps mit Kuchengeschmack"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "chronisches Grinsen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "doppelte Penetration"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Sklaven"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "reife Frauen ab 40!"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "peinlich dicke Zehen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "versehentliches Ableben"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "eine unhöfliche Enthauptung"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Wonder Woman"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein Fötus"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein Kruzifix"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Kreuzzüge"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "von Mundwasser betrunken werden"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein Pferdekopf"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "eine haarige Eichel"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "zivile Opfer"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Obdachlose"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Natursekt Spiele"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Freunde mit Extras"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Fingermalerei"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein Pantomime, der einen Schlaganfall hat"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Viagra"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein Trinkpäckchen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein Mann, der seinen Orgasmus vortäuscht"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "einen Huf in den Arsch"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "sexuelle Spannungen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Selbsthass"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein Schönheitsfleck"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ich bin bereit!"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Quallenfischen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "SCHOKOLADE!"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Flittchen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Alkohol"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Shisha"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Muschiklaus"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Bauer sucht Frau"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Galoppel Hans"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Gammelobst"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "feucht"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Ü40 Partys"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Zwergenwerfen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Terroristen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Hundebabies!"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "ein Affe, der Zigaretten raucht"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Katapulte"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Macht"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Grabschändung"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "eine freche schwarze Frau"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Mundherpes"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Einnässen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Zehn- bis Zwölfjährige"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Geister"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Pumuckl"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Pommes!"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "heimliches Arschkratzen"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Oralsex nicht erwidern"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "Kinnhaken"));
        pia_deck.addWhiteCard(new com.afms.cahgame.game.Card(Colour.WHITE, "meine Genitalien"));
        return pia_deck;
    }
}
